config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :projects do
    collection { post :import }
    resources :tasks do
      resources :comments
    end
  end

  root 'home#index'
end

app/models/task.rb
# frozen_string_literal: true

class Task < ApplicationRecord
  enum status: { to_do: 0, in_progress: 1, dev_done: 2, ready_for_testing: 3 }
  belongs_to :project
  has_many :comments, dependent: :destroy
  validates :title, :description, :status, :delivery_date, presence: true
  ransack_alias :search, :title_or_description
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

class TasksController < ApplicationController
  before_action :find_task, only: %i[show edit update destroy]

  def index
    @q = find_project.tasks.ransack(params[:q])
    @tasks = pagination(@q.result)
    @task_count = find_project.tasks.count
    @tasks_project_name = find_project.name
  end

  def new
    @task = find_project.tasks.new
  end

  def edit; end

  def show
    @comments = pagination(find_task.comments)
    images = []
    @comments.each do |comment|
      comment.pictures.attachments.each do |image|
        images << { image_id: image.id, image_url: url_for(image) }
      end
      respond_to do |format|
        format.html
        format.json { render json: { success: true, comment: @comment.attributes.merge(pictures: images) } }
      end
    end
  end

  def create
    @task = find_project.tasks.new(task_params)
    if @task.save
      flash[:success] = "Task created successfully."
      redirect_to project_tasks_path(project_id: @task.project_id)
    else
      render :new
    end
  end

  def update
    if @task.update(task_params)
      flash[:success] = "Task updated successfully."
      redirect_to project_tasks_path(project_id: @task.project_id)
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    flash[:success] = "Task deleted successfully."  
    redirect_to project_tasks_path(project_id: @task.project_id)
  end

  private

  def find_project
    Project.find(params[:project_id])
  end

  def find_task
    @task = Task.find(params[:id])
  end

  def find_comment
    @comment = Comment.find_by(id: params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :description, :status, :delivery_date, :project_id)
  end
end

app/helpers/tasks_helper.rb
# frozen_string_literal: true

module TasksHelper
  def set_task_status
    enum_to_options_array(Task, 'status')
  end
end

app/views/tasks/_form.html.erb
<div class="card-body">
  <%= form_with(model: task, url: url, method: method, local: true) do |form| %>
    <div class="row">
      <div class="col-md-5">
        <div class="form-group">
          <%= form.label :title, class: "form-control-label bmd-label-floating" do %>Title
            <span class='text-danger'>*</span>
          <% end %>
          <%= form.text_field :title, class: 'form-control', placeholder: 'Enter task title', required: true %>
        </div>
      </div>
      <div class="col-md-5">
        <div class="form-group">
          <%= form.label :description, class: "form-control-label bmd-label-floating" do %>Description
            <span class='text-danger'>*</span>
          <% end %>
          <%= form.text_field :description, class: 'form-control', placeholder: 'Enter task description', required: true %>
        </div>
      </div>
      <div class="col-md-5">
        <div class="form-group">
          <%= form.label :status, class: "form-control-label" do %>Status
            <span class='text-danger'>*</span>
          <% end %>
          <%= form.select :status, options_for_select(set_task_status, form.object.status), { include_blank: '-- Select task status --' },  class: 'form-control dropdown', required: true %>
        </div>
      </div>
      <div class="col-md-5">
        <div class="form-group">
          <%= form.label :delivery_date, class: "form-control-label" %>
          <%= form.date_field :delivery_date, class: 'form-control datepicker', autocomplete: 'off', placeholder: "select delivery date", required: true %>
        </div>
      </div>
    </div><br>
    <div class="bottom-btn two-btn btn-row">
      <%= link_to project_tasks_path, class: 'btn btn-outline-secondary btn-sm' do %>
        <i class="fa fa-arrow-left left" aria-hidden="true"></i>Back
      <% end %>
      <%= form.button(type: 'submit', class: "btn btn-primary btn-sm") do %>
        <i class="fa fa-check left" aria-hidden="true"></i><%= pro_submit_button %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/tasks/edit.html.erb
<div class="main-wrap">
  <div class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-8">
          <div class="card">
            <div class="card-header card-header-primary">
              <h4 class="card-title">Edit Task</h4>
              <p class="card-category">Task Details</p>
            </div>
            <%= render 'form', task: @task, url: project_task_path(@task), method: :put %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tasks/index.html.erb
<div class="main-wrap">
  <div class="wrapper ">
    <div class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="card">
            <div class="card-header card-header-primary">
              <h4 class="card-title "><b>Project Name - <%= @tasks_project_name %></b></h4>
              <h4 class="card-title "><b>Total Tasks - <%= @task_count %></b></h4>
              <%= link_to new_project_task_path, class: 'btn btn-primary btn-sm float-right' do %>
                <i class="fa fa-plus left" aria-hidden="true"></i> <span>Task</span>
              <% end %>
            </div>
            <div class="card-body">
              <div class='row mb-2'>
                <div class="col-md-12">
                  <%= search_form_for @q, url: project_tasks_path do |f| %>
                    <div class="input-group">
                      <%= f.search_field :search_cont, value: params.dig('q', 'search_cont'), class: 'form-control search', placeholder: "Search task by name or description..."  %>
                      <div class="input-group-append">
                        <%= f.submit "search", class: "btn btn-outline-primary btn-sm" %>
                      </div>
                    </div>  
                  <% end %>
                </div>
              </div>            
              <div class="table-responsive">                
                <% if @tasks.present? %>
                  <table class="table">
                    <thead>
                      <tr>
                        <th scope="col">#</th>
                        <th scope="col"><%= sort_link(@q, :title) %></th>
                        <th scope="col"><%= sort_link(@q, :description) %></th>
                        <th scope="col"><%= sort_link(@q, :status) %></th>
                        <th scope="col"><%= sort_link(@q, :delivery_date) %></th>
                        <th scope="col" colspan="2">Action</th>
                      </tr>
                    </thead>
                    <tbody>
                      <% @tasks.each_with_index do |task, index| %>
                        <tr>
                          <td scope="row"><%= index_count_increment(index) %></td>
                          <td scope="row"><%= link_to humanize_data(task.title), project_task_path(id: task.id) %></td>
                          <td scope="row"><%= humanize_data(task.description) %></td>
                          <td scope="row"><%= humanize_data(task.status) %></td>
                          <td scope="row"><%= formatted_date(task.delivery_date) %></td>
                          <td scope="row">
                            <%= link_to edit_project_task_path(id: task.id) do %>
                              <i class='fa fa-edit pd-6' data-placement="bottom" title='Edit'></i>
                            <% end %>
                            <%= link_to project_task_path(id: task.id), method: :delete, data: { confirm: "Are you sure want to delete task?" }, class: 'confirm disable-right-click' do %>
                              <i class='fa fa-trash pd-6' data-placement="bottom" title='Delete'></i>
                            <% end %>
                          </td>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
                  <%= paginate @tasks %>
                <% end %>
              <div class="bottom-btn two-btn btn-row">
                <%= link_to projects_path, class: 'btn btn-outline-secondary btn-sm' do %>
                  <i class="fa fa-arrow-left left" aria-hidden="true"></i>Back
                <% end %>
              </div>                
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tasks/new.html.erb
<div class="main-wrap">
  <div class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-8">
          <div class="card">
            <div class="card-header card-header-primary">
              <h4 class="card-title">Create Task</h4>
              <p class="card-category">Task Details</p>
            </div>
            <%= render 'form', task: @task, url: project_tasks_path, method: :post %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tasks/show.html.erb
<div class="main-wrap">
  <div class="card">
    <div class="card-header">
      <strong class="card-title">Task view</strong>
    </div>
    <div class="card-body">
      <div class="row data-listing">
        <div class="col-lg-3 col-sm-6">
          <p>
            <strong>Title: </strong>
            <%= @task.title %>
          </p>
          <p>
            <strong>Description: </strong>
            <%= @task.description %>
          </p>
        </div>
      </div><hr>
      <div class="add-comment row">
        <div class="col-sm-6">
          <%= form_for :comment, url: project_task_comments_path(task_id: @task.id) do |f| %>
            <div class="form-group">
              <%= f.text_area :description, class: "form-control", placeholder: "Write comment for the task...", rows: 5, required: true %>
            </div>

            <div class="form-group col-sm-12">
              <%= f.label :pictures, class: "form-control-label" %>
              <div class="custom-file">
                <%= f.file_field :pictures, multiple: true, class: "custom-file-input", id:"customFile" %>
                <label class="custom-file-label" for="customFile">Choose image</label>
              </div>
            </div>           

            <div class="form-group">
              <%= f.submit "Add comment", class: "btn btn-success" %>
            </div>
          <% end %>
        </div>
      </div><hr>
      <div class="all-comments row">
        <div class="col-sm-12">
          <% if @comments.present? %>
            <h3>Comments</h3>
          <% end %>
          <% @comments.each do |comment| %>
            <div class="comment">
              <p class="comment-owner">
                <p><u><b>Comment:</b></u>
                  <%= humanize_data(comment.description) %>
                </p>
                <% if comment.try(:pictures).attached? %>
                <div class="col-md-12">
                  <table class='table table-borderless ortanisation-details'>
                    <tbody>
                      <tr>
                        <td>
                          <div class="row uploadedImages">                
                            <p class='table-head'>Pictures:</p>
                            <div>
                              <div class="uploadedImages">
                                <% comment.pictures.each do |image| %>
                                  <figure class="upload-image">
                                    <% if image.present? %>
                                      <%= image_tag image %>
                                    <% end %>
                                  </figure>
                                <% end %>
                              </div>
                            </div>
                          </div>
                        </td>
                      </tr>
                    </tbody>
                  </table>
                </div>
                <% end %>
                <span class="comment-created small">
                  <%= humanize_data(time_ago_in_words(comment.created_at)) %> ago
                </span>
                <span class="edit-comment">
                  <%= link_to edit_project_task_comment_path(task_id: comment.task_id, id: comment.id, project_id: comment.task.project.id) do %>
                    <i class='fa fa-edit pd-6' data-placement="bottom" title='Edit'></i>
                  <% end %>
                </span>
                <span class="delete-comment">
                  <%= link_to project_task_comment_path(task_id: comment.task_id, id: comment.id), method: :delete, data: { confirm: 'Are you sure want to delete comment?' } do %>
                    <i class='fa fa-trash pd-6' data-placement="bottom" title='Delete'></i>
                  <% end %>
                </span>
              </p><hr>
            </div>
          <% end %>
        </div>
      </div>
      <%= paginate @comments %>    
    </div>
  </div>
</div>