config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :projects do
    collection { post :import }
    resources :tasks do
      resources :comments
    end
  end

  root 'home#index'
end

app/models/project.rb
# frozen_string_literal: true

class Project < ApplicationRecord
  has_many :tasks, dependent: :destroy
  has_many :comments, through: :task
  enum status: { start: 0, on_hold: 1, complete: 2 }
  validates :name, :description, :status, :start_date, :end_date, :internal_demo_date, presence: true
  ransack_alias :search, :name

  def self.to_csv(fields = column_names, options = {})
    CSV.generate(options) do |csv|
      csv << fields
      all.each do |project|
        csv << project.attributes.values_at(*fields)
      end
    end
  end

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      project_hash = row.to_hash
      project = find_or_create_by!(name: project_hash['name'], description: project_hash['description'], status: project_hash['status'], start_date: project_hash['start_date'], end_date: project_hash['end_date'], internal_demo_date: project_hash['internal_demo_date'])
      project.update(project_hash)
    end
  end
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  before_action :find_project, only: %i[show edit update destroy]

  def index
    @q = Project.ransack(params[:q])
    @projects = pagination(@q.result)
    @project_list = Project.all
    respond_to do |format|
      format.html
      format.csv { send_data @project_list.to_csv(['name', 'description', 'status', 'start_date', 'end_date', 'internal_demo_date']) }
    end
  end

  def import
    Project.import(params[:file])
    redirect_to projects_path, notice: "Projects imported."
  end

  def show; end

  def new
    @project = Project.new
  end

  def edit; end

  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to projects_path, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to projects_path, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def find_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name, :description, :status, :start_date, :end_date, :internal_demo_date)
  end
end

app/helpers/projects_helper.rb
# frozen_string_literal: true

module ProjectsHelper
  def set_project_status
    enum_to_options_array(Project, 'status')
  end

  def pro_submit_button
    action_name == 'edit' ? "Update" : "Create"
  end
end

app/views/projects/_form.html.erb
<div class="card-body">
  <%= form_with(model: @project, local: true, id: 'project_form') do |form| %>
    <div class="row">
      <div class="col-md-5">
        <div class="form-group">
          <%= form.label :name, class: "form-control-label bmd-label-floating" do %>Name
            <span class='text-danger'>*</span>
          <% end %>
          <%= form.text_field :name, class: 'form-control', placeholder: 'Enter project name', required: true %>
        </div>
      </div>
      <div class="col-md-5">
        <div class="form-group">
          <%= form.label :description, class: "form-control-label bmd-label-floating" do %>Description
            <span class='text-danger'>*</span>
          <% end %>
          <%= form.text_field :description, class: 'form-control', placeholder: 'Enter project description', required: true %>
        </div>
      </div>
      <div class="col-md-5">
        <div class="form-group">
          <%= form.label :status, class: "form-control-label" do %>Status
            <span class='text-danger'>*</span>
          <% end %>
          <%= form.select :status, options_for_select(set_project_status, form.object.status), { include_blank: '-- Select project status --' },  class: 'form-control dropdown', required: true %>
        </div>
      </div>
      <div class="col-md-5">
        <div class="form-group">
          <%= form.label :start_date, class: "form-control-label" %>
          <%= form.date_field :start_date, class: 'form-control datepicker', autocomplete: 'off', placeholder: "select start date", required: true %>
        </div>
      </div>
      <div class="col-md-5">
        <div class="form-group">
          <%= form.label :end_date, class: "form-control-label" %>
          <%= form.date_field :end_date, class: 'form-control datepicker', autocomplete: 'off', placeholder: "select start date", required: true %>
        </div> 
      </div>
      <div class="col-md-5">
        <div class="form-group">
          <%= form.label :internal_demo_date, class: "form-control-label" %>
          <%= form.date_field :internal_demo_date, class: 'form-control datepicker', autocomplete: 'off', placeholder: "select start date", required: true %>
        </div>  
      </div>
    </div><br>
    <div class="bottom-btn two-btn btn-row">
      <%= link_to projects_path, class: 'btn btn-outline-secondary btn-sm' do %>
        <i class="fa fa-arrow-left left" aria-hidden="true"></i>Back
      <% end %>
      <%= form.button(type: 'submit', class: "btn btn-primary btn-sm") do %>
        <i class="fa fa-check left" aria-hidden="true"></i><%= pro_submit_button %>
      <% end %>
    </div>
  <% end %>
</div>
<script type="text/javascript">
  DatePicker.initDatePicker();
  Project.validateProject();
</script>

app/views/projects/edit.html.erb
<div class="main-wrap">
  <div class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-8">
          <div class="card">
            <div class="card-header card-header-primary">
              <h4 class="card-title">Edit Project</h4>
              <p class="card-category">Project Details</p>
            </div>
            <%= render 'form' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/projects/index.html.erb
<div class="main-wrap">
  <div class="wrapper ">
    <div class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="card">
            <div class="card-header card-header-primary">
              <h4 class="card-title "><b>Total Project - <%= Project.count %></b></h4>

              <%= link_to "Export CSV", projects_path(format: "csv"), class: "btn btn-primary" %>
              <%= form_tag import_projects_path, multipart: true, class: 'form-inline' do %>

                <div class="form-group">
                  <label for="file"><h4><u>Click Here Upload File</u></h4></label>
                  <%= file_field_tag "file" %>
                </div>

                <div class="form-group">
                  <%= submit_tag "Submit File to Import CSV", class: 'btn btn-info' %>
                </div>
              <% end %>

              <%= link_to new_project_path, class: 'btn btn-primary btn-sm float-right' do %>
                <i class="fa fa-plus left" aria-hidden="true"></i> <span>Project</span>
              <% end %>
            </div>
            <div class="card-body">
              <div class='row mb-2'>
                <div class="col-md-12">
                  <%= search_form_for @q, url: projects_path do |f| %>
                    <div class="input-group">
                      <%= f.search_field :search_cont, value: params.dig('q', 'search_cont'), class: 'form-control search', placeholder: "Search projects by name..."  %>
                      <div class="input-group-append">
                        <%= f.submit "search", class: "btn btn-outline-primary btn-sm" %>
                      </div>
                    </div>
                  <% end %>
                </div>
              </div>
              <div class="table-responsive">
                <% if @projects.present? %>
                  <table class="table">
                    <thead>
                      <tr>
                        <th scope="col">#</th>
                        <th scope="col"><%= sort_link(@q, :name) %></th>
                        <th scope="col"><%= sort_link(@q, :status) %></th>
                        <th scope="col"><%= sort_link(@q, :start_date) %></th>
                        <th scope="col"><%= sort_link(@q, :end_date) %></th>
                        <th scope="col"><%= sort_link(@q, :internal_demo_date) %></th>
                        <th scope="col" colspan="2">Action</th>
                      </tr>
                    </thead>
                    <tbody>
                      <% @projects.each_with_index do |project, index| %>
                        <tr>
                          <td scope="row"><%= index_count_increment(index) %></td>
                          <td scope="row"><%= link_to humanize_data(project.name), project_tasks_path(project_id: project.id) %></td>
                          <td scope="row"><%= humanize_data(project.status) %></td>
                          <td scope="row"><%= formatted_date(project.start_date) %></td>
                          <td scope="row"><%= formatted_date(project.end_date) %></td>
                          <td scope="row"><%= formatted_date(project.internal_demo_date) %></td>
                          <td scope="row">
                            <%= link_to edit_project_path(id: project.id) do %>
                              <i class='fa fa-edit pd-6' data-placement="bottom" title='Edit'></i>
                            <% end %>
                            <%= link_to project_path(id: project.id), method: :delete, data: { confirm: "Are you sure want to delete project?" }, class: 'confirm disable-right-click' do %>
                              <i class='fa fa-trash pd-6' data-placement="bottom" title='Delete'></i>
                            <% end %>
                          </td>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
                  <%= paginate @projects %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<div class="main-wrap">
  <div class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-8">
          <div class="card">
            <div class="card-header card-header-primary">
              <h4 class="card-title">Create Project</h4>
              <p class="card-category">Project Details</p>
            </div>
            <%= render 'form' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/projects/show.html.erb
<div class="main-wrap">
  <div class="wrapper ">
    <div class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="card">
            <div class="card-header card-header-primary">
              <h4 class="card-title "><b>Project Details</b></h4>
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table">
                  <thead>
                    <tr>
                      <th scope="col">Name</th>
                      <th scope="col">Status</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td scope="row"><%= @project.name %></td>
                      <td scope="row"><%= @project.status %></td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>